export interface RepoContextPolicy {
  maxArchiveBytes: number;
  maxExtractedTextBytes: number;
  maxSingleFileBytes: number;
  maxIndexedFileChars: number;
  maxReadFileChars: number;
  maxReadRelatedFiles: number;
  maxManifestEntriesReturned: number;
  maxSymbolSkeletonChars: number;
  maxModuleMapChars: number;
  maxSearchResults: number;
  maxPaperDigestChars: number;
  maxPaperSectionChars: number;
  githubRequestTimeoutMs: number;
  githubRequestRetries: number;
  allowedExtensions: string[];
  allowedBasenames: string[];
  ignoredDirs: string[];
  priorityFilenames: string[];
  priorityDirs: string[];
}

export const DEFAULT_REPO_POLICY: RepoContextPolicy = {
  maxArchiveBytes: 80 * 1024 * 1024,
  maxExtractedTextBytes: 12 * 1024 * 1024,
  maxSingleFileBytes: 512 * 1024,
  maxIndexedFileChars: 300_000,
  maxReadFileChars: 180_000,
  maxReadRelatedFiles: 12,
  maxManifestEntriesReturned: 500,
  maxSymbolSkeletonChars: 80_000,
  maxModuleMapChars: 60_000,
  maxSearchResults: 30,
  maxPaperDigestChars: 40_000,
  maxPaperSectionChars: 16_000,
  githubRequestTimeoutMs: 30_000,
  githubRequestRetries: 2,
  allowedExtensions: [
    ".py",
    ".ipynb",
    ".ts",
    ".tsx",
    ".js",
    ".jsx",
    ".java",
    ".kt",
    ".scala",
    ".cpp",
    ".cc",
    ".c",
    ".h",
    ".hpp",
    ".rs",
    ".go",
    ".swift",
    ".yaml",
    ".yml",
    ".json",
    ".toml",
    ".ini",
    ".cfg",
    ".conf",
    ".md",
    ".rst",
    ".txt",
  ],
  allowedBasenames: [
    "dockerfile",
    "makefile",
    "requirements.txt",
    "environment.yml",
    "pyproject.toml",
    "setup.py",
    "setup.cfg",
    "package.json",
  ],
  ignoredDirs: [
    ".git",
    ".github",
    "node_modules",
    "dist",
    "build",
    "coverage",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    ".venv",
    "venv",
    "env",
    "site-packages",
    "data",
    "datasets",
    "weights",
    "checkpoints",
    "pretrained",
    "runs",
    "logs",
    "wandb",
    "assets",
    "figures",
    "images",
    "media",
    "docs",
    "doc",
    "examples",
    "example",
    "demo",
    "demos",
  ],
  priorityFilenames: [
    "model.py",
    "models.py",
    "network.py",
    "networks.py",
    "module.py",
    "modules.py",
    "architecture.py",
    "train.py",
    "trainer.py",
    "training.py",
    "main.py",
    "run.py",
    "finetune.py",
    "loss.py",
    "losses.py",
    "criterion.py",
    "objective.py",
    "dataset.py",
    "datasets.py",
    "data.py",
    "dataloader.py",
    "transforms.py",
    "config.py",
    "config.yaml",
    "default.yaml",
    "eval.py",
    "evaluate.py",
    "test.py",
    "inference.py",
    "predict.py",
    "readme.md",
    "requirements.txt",
    "environment.yml",
    "pyproject.toml",
    "setup.py",
  ],
  priorityDirs: [
    "src",
    "models",
    "model",
    "networks",
    "modules",
    "architectures",
    "train",
    "training",
    "trainer",
    "engine",
    "data",
    "datasets",
    "dataloader",
    "loss",
    "losses",
    "criterions",
    "configs",
    "config",
    "eval",
    "evaluation",
    "inference",
    "scripts",
  ],
};
